version: "3.1"

services:
  backend:
    env_file:
      - .env
    container_name: todo-list-gmi-backend
    build:
      dockerfile: dockerfile.backend
      context: .
    restart: always
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - type: bind
        source: ./backend/src
        target: /src
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: todo-list-gmi-database
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 4s
      timeout: 4s
      retries: 9999
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  pgadmin:
    container_name: todo-list-gmi-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
