version: "3.1"

services:
  backend:
    env_file:
      - .env
    container_name: todo-list-gmi-backend
    build:
      dockerfile: dockerfile.backend
      context: .
    restart: always
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - type: bind
        source: ./backend/src
        target: /src

  db:
    container_name: todo-list-gmi-database
    image: postgres:latest
    restart: always
    # Create volume in order to persist data after container is removed
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Password for Postgres user
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  pgdata:
